spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=bettle;integratedSecurity=true;
    username: bettle
    password: bettle
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  messages:
    basename: i18n/messages
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR