spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/bettle
      username: bettle
      password: bettle
  messages:
    basename: i18n/messages
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR